[package]
name = "cuh4/ragdollworks"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
trove = "sparefuse/trove@1.6.0"
signal = "sleitnick/signal@2.0.3"
conch = "alicesaidhi/conch@0.2.3"
conch_ui = "alicesaidhi/conch-ui@0.2.3"