--------------------------------------------------------
-- [Ragdollworks] Rbx Assets
--------------------------------------------------------

--[[
    ----------------------------

    Copyright (C) 2025 Cuh4 - All Rights Reserved
        - Unauthorized copying of this file, via any medium is strictly prohibited
        - Proprietary and confidential

    CREDIT:
        Author(s): @Cuh4 (GitHub)
        GitHub Repository: https://github.com/Cuh4/RagdollWorks

    ----------------------------
]]

-------------------------------
-- // Main
-------------------------------

return {
    CURSOR_ICON = "rbxassetid://118815884093849",
    UNKNOWN_ICON = "rbxassetid://139531674672176"
}